version: 2

# Define the build process for Sphinx
sphinx:
  configuration: docs/conf.py

# Specify the Python environment
python:
  version: 3.8  # Replace with your project's required Python version
  install:
    - requirements: docs/requirements.txt
